# frozen_string_literal: true

require_relative "trophy_api_client/types/metric_status"
require_relative "trophy_api_client/types/streak_frequency"
require_relative "trophy_api_client/types/base_streak_response"
require_relative "trophy_api_client/types/increment_metric_streak_response"
require_relative "trophy_api_client/types/streak_response_streak_history_item"
require_relative "trophy_api_client/types/streak_response"
require_relative "trophy_api_client/types/achievement_response"
require_relative "trophy_api_client/types/metric_response"
require_relative "trophy_api_client/types/updated_user"
require_relative "trophy_api_client/types/upserted_user"
require_relative "trophy_api_client/types/user"
require_relative "trophy_api_client/types/error_body"
require_relative "trophy_api_client/types/achievement_completion_response"
require_relative "trophy_api_client/types/event_response"
