# frozen_string_literal: true

require_relative "trophy_api_client/types/metric_status"
require_relative "trophy_api_client/types/streak_frequency"
require_relative "trophy_api_client/types/streak_response"
require_relative "trophy_api_client/types/multi_stage_achievement_response"
require_relative "trophy_api_client/types/one_off_achievement_response"
require_relative "trophy_api_client/types/metric_response"
require_relative "trophy_api_client/types/updated_user"
require_relative "trophy_api_client/types/upserted_user"
require_relative "trophy_api_client/types/user"
require_relative "trophy_api_client/types/error_body"
require_relative "trophy_api_client/types/achievement_completion_response"
require_relative "trophy_api_client/types/event_response_metrics_item"
require_relative "trophy_api_client/types/event_response"
