name: Publish Ruby Gem

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Verify Rakefile and tasks
        run: bundle exec rake --tasks  # Debugging step

      - name: Release Gem
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          bundle exec rake release
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBY_API_KEY }}
